{
    "active_lock_reason": null,
    "assignee": null,
    "assignees": [],
    "author_association": "NONE",
    "body": "JFYI, I'm getting the following error when trying to execute the models/image/mnist/convolutional.py example (Python 2.7.10 in PyEnv, on Xubuntu 14.04, 64bit):\n\n``` bash\n[samuel site-packages]$ pwd\n/home/samuel/.pyenv/versions/2.7.10/lib/python2.7/site-packages\n[samuel site-packages]$ python tensorflow/models/image/mnist/convolutional.py\nTraceback (most recent call last):\n  File \"tensorflow/models/image/mnist/convolutional.py\", line 12, in <module>\n    import tensorflow.python.platform\n  File \"/home/samuel/.pyenv/versions/2.7.10/lib/python2.7/site-packages/tensorflow/__init__.py\", line 4, in <module>\n    from tensorflow.python import *\n  File \"/home/samuel/.pyenv/versions/2.7.10/lib/python2.7/site-packages/tensorflow/python/__init__.py\", line 22, in <module>\n    from tensorflow.python.client.client_lib import *\n  File \"/home/samuel/.pyenv/versions/2.7.10/lib/python2.7/site-packages/tensorflow/python/client/client_lib.py\", line 35, in <module>\n    from tensorflow.python.client.session import InteractiveSession\n  File \"/home/samuel/.pyenv/versions/2.7.10/lib/python2.7/site-packages/tensorflow/python/client/session.py\", line 11, in <module>\n    from tensorflow.python import pywrap_tensorflow as tf_session\n  File \"/home/samuel/.pyenv/versions/2.7.10/lib/python2.7/site-packages/tensorflow/python/pywrap_tensorflow.py\", line 28, in <module>\n    _pywrap_tensorflow = swig_import_helper()\n  File \"/home/samuel/.pyenv/versions/2.7.10/lib/python2.7/site-packages/tensorflow/python/pywrap_tensorflow.py\", line 24, in swig_import_helper\n    _mod = imp.load_module('_pywrap_tensorflow', fp, pathname, description)\nImportError: /home/samuel/.pyenv/versions/2.7.10/lib/python2.7/site-packages/tensorflow/python/_pywrap_tensorflow.so: undefined symbol: PyUnicodeUCS4_FromStringAndSize\n```\n\nWill see if I can figure out something, but thought to report in the meanwhile.\n",
    "closed_at": "2015-11-13T22:26:33Z",
    "closed_by": {
        "avatar_url": "https://avatars.githubusercontent.com/u/463737?v=4",
        "events_url": "https://api.github.com/users/vrv/events{/privacy}",
        "followers_url": "https://api.github.com/users/vrv/followers",
        "following_url": "https://api.github.com/users/vrv/following{/other_user}",
        "gists_url": "https://api.github.com/users/vrv/gists{/gist_id}",
        "gravatar_id": "",
        "html_url": "https://github.com/vrv",
        "id": 463737,
        "login": "vrv",
        "node_id": "MDQ6VXNlcjQ2MzczNw==",
        "organizations_url": "https://api.github.com/users/vrv/orgs",
        "received_events_url": "https://api.github.com/users/vrv/received_events",
        "repos_url": "https://api.github.com/users/vrv/repos",
        "site_admin": false,
        "starred_url": "https://api.github.com/users/vrv/starred{/owner}{/repo}",
        "subscriptions_url": "https://api.github.com/users/vrv/subscriptions",
        "type": "User",
        "url": "https://api.github.com/users/vrv"
    },
    "comments": 6,
    "comments_url": "https://api.github.com/repos/tensorflow/tensorflow/issues/24/comments",
    "created_at": "2015-11-09T18:06:21Z",
    "events_url": "https://api.github.com/repos/tensorflow/tensorflow/issues/24/events",
    "html_url": "https://github.com/tensorflow/tensorflow/issues/24",
    "id": 115932607,
    "labels": [],
    "labels_url": "https://api.github.com/repos/tensorflow/tensorflow/issues/24/labels{/name}",
    "locked": false,
    "milestone": null,
    "node_id": "MDU6SXNzdWUxMTU5MzI2MDc=",
    "number": 24,
    "performed_via_github_app": null,
    "reactions": {
        "+1": 0,
        "-1": 0,
        "confused": 0,
        "eyes": 0,
        "heart": 0,
        "hooray": 0,
        "laugh": 0,
        "rocket": 0,
        "total_count": 0,
        "url": "https://api.github.com/repos/tensorflow/tensorflow/issues/24/reactions"
    },
    "repository_url": "https://api.github.com/repos/tensorflow/tensorflow",
    "state": "closed",
    "state_reason": "completed",
    "timeline_url": "https://api.github.com/repos/tensorflow/tensorflow/issues/24/timeline",
    "title": "Problems running the image example (Python 2.7.10, PyEnv, Xubuntu 14.04 64bit)",
    "updated_at": "2016-11-23T09:00:41Z",
    "url": "https://api.github.com/repos/tensorflow/tensorflow/issues/24",
    "user": {
        "avatar_url": "https://avatars.githubusercontent.com/u/125003?v=4",
        "events_url": "https://api.github.com/users/samuell/events{/privacy}",
        "followers_url": "https://api.github.com/users/samuell/followers",
        "following_url": "https://api.github.com/users/samuell/following{/other_user}",
        "gists_url": "https://api.github.com/users/samuell/gists{/gist_id}",
        "gravatar_id": "",
        "html_url": "https://github.com/samuell",
        "id": 125003,
        "login": "samuell",
        "node_id": "MDQ6VXNlcjEyNTAwMw==",
        "organizations_url": "https://api.github.com/users/samuell/orgs",
        "received_events_url": "https://api.github.com/users/samuell/received_events",
        "repos_url": "https://api.github.com/users/samuell/repos",
        "site_admin": false,
        "starred_url": "https://api.github.com/users/samuell/starred{/owner}{/repo}",
        "subscriptions_url": "https://api.github.com/users/samuell/subscriptions",
        "type": "User",
        "url": "https://api.github.com/users/samuell"
    }
}