{
    "active_lock_reason": null,
    "assignee": null,
    "assignees": [],
    "author_association": "NONE",
    "body": "Django 3.1.4\r\nPython 3.9.1\r\nIPython 7.19.0\r\nError occurs during import:\r\n\r\n```Traceback (most recent call last):\r\n  File \"/usr/local/lib/python3.9/site-packages/IPython/terminal/ptutils.py\", line 113, in get_completions\r\n    yield from self._get_completions(body, offset, cursor_position, self.ipy_completer)\r\n  File \"/usr/local/lib/python3.9/site-packages/IPython/terminal/ptutils.py\", line 129, in _get_completions\r\n    for c in completions:\r\n  File \"/usr/local/lib/python3.9/site-packages/IPython/core/completer.py\", line 438, in _deduplicate_completions\r\n    completions = list(completions)\r\n  File \"/usr/local/lib/python3.9/site-packages/IPython/core/completer.py\", line 1818, in completions\r\n    for c in self._completions(text, offset, _timeout=self.jedi_compute_type_timeout/1000):\r\n  File \"/usr/local/lib/python3.9/site-packages/IPython/core/completer.py\", line 1861, in _completions\r\n    matched_text, matches, matches_origin, jedi_matches = self._complete(\r\n  File \"/usr/local/lib/python3.9/site-packages/IPython/core/completer.py\", line 2029, in _complete\r\n    completions = self._jedi_matches(\r\n  File \"/usr/local/lib/python3.9/site-packages/IPython/core/completer.py\", line 1373, in _jedi_matches\r\n    interpreter = jedi.Interpreter(\r\n  File \"/usr/local/lib/python3.9/site-packages/jedi/api/__init__.py\", line 725, in __init__\r\n    super().__init__(code, environment=environment,\r\nTypeError: __init__() got an unexpected keyword argument 'column'\r\n\r\nDuring handling of the above exception, another exception occurred:\r\n\r\nTraceback (most recent call last):\r\n  File \"/src/manage.py\", line 15, in <module>\r\n    execute_from_command_line(sys.argv)\r\n  File \"/usr/local/lib/python3.9/site-packages/django/core/management/__init__.py\", line 401, in execute_from_command_line\r\n    utility.execute()\r\n  File \"/usr/local/lib/python3.9/site-packages/django/core/management/__init__.py\", line 395, in execute\r\n    self.fetch_command(subcommand).run_from_argv(self.argv)\r\n  File \"/usr/local/lib/python3.9/site-packages/django/core/management/base.py\", line 330, in run_from_argv\r\n    self.execute(*args, **cmd_options)\r\n  File \"/usr/local/lib/python3.9/site-packages/django/core/management/base.py\", line 371, in execute\r\n    output = self.handle(*args, **options)\r\n  File \"/usr/local/lib/python3.9/site-packages/django/core/management/commands/shell.py\", line 100, in handle\r\n    return getattr(self, shell)(options)\r\n  File \"/usr/local/lib/python3.9/site-packages/django/core/management/commands/shell.py\", line 36, in ipython\r\n    start_ipython(argv=[])\r\n  File \"/usr/local/lib/python3.9/site-packages/IPython/__init__.py\", line 126, in start_ipython\r\n    return launch_new_instance(argv=argv, **kwargs)\r\n  File \"/usr/local/lib/python3.9/site-packages/traitlets/config/application.py\", line 845, in launch_instance\r\n    app.start()\r\n  File \"/usr/local/lib/python3.9/site-packages/IPython/terminal/ipapp.py\", line 356, in start\r\n    self.shell.mainloop()\r\n  File \"/usr/local/lib/python3.9/site-packages/IPython/terminal/interactiveshell.py\", line 564, in mainloop\r\n    self.interact()\r\n  File \"/usr/local/lib/python3.9/site-packages/IPython/terminal/interactiveshell.py\", line 547, in interact\r\n    code = self.prompt_for_code()\r\n  File \"/usr/local/lib/python3.9/site-packages/IPython/terminal/interactiveshell.py\", line 473, in prompt_for_code\r\n    text = self.pt_app.prompt(\r\n  File \"/usr/local/lib/python3.9/site-packages/prompt_toolkit/shortcuts/prompt.py\", line 1013, in prompt\r\n    return self.app.run(set_exception_handler=set_exception_handler)\r\n  File \"/usr/local/lib/python3.9/site-packages/prompt_toolkit/application/application.py\", line 816, in run\r\n    return loop.run_until_complete(\r\n  File \"/usr/local/lib/python3.9/asyncio/base_events.py\", line 642, in run_until_complete\r\n    return future.result()\r\n  File \"/usr/local/lib/python3.9/site-packages/prompt_toolkit/application/application.py\", line 783, in run_async\r\n    return await _run_async2()\r\n  File \"/usr/local/lib/python3.9/site-packages/prompt_toolkit/application/application.py\", line 771, in _run_async2\r\n    await self.cancel_and_wait_for_background_tasks()\r\n  File \"/usr/local/lib/python3.9/site-packages/prompt_toolkit/application/application.py\", line 872, in cancel_and_wait_for_background_tasks\r\n    await task\r\n  File \"/usr/local/lib/python3.9/site-packages/prompt_toolkit/buffer.py\", line 1854, in new_coroutine\r\n    await coroutine(*a, **kw)\r\n  File \"/usr/local/lib/python3.9/site-packages/prompt_toolkit/buffer.py\", line 1683, in async_completer\r\n    async for completion in self.completer.get_completions_async(\r\n  File \"/usr/local/lib/python3.9/site-packages/prompt_toolkit/completion/base.py\", line 269, in get_completions_async\r\n    async for completion in completer.get_completions_async(\r\n  File \"/usr/local/lib/python3.9/site-packages/prompt_toolkit/completion/base.py\", line 196, in get_completions_async\r\n    for item in self.get_completions(document, complete_event):\r\n  File \"/usr/local/lib/python3.9/site-packages/IPython/terminal/ptutils.py\", line 116, in get_completions\r\n    exc_type, exc_value, exc_tb = sys.exc_info()\r\nNameError: name 'sys' is not defined\r\n```\r\n\r\nBut when I just call `import sys` this it works:\r\n\r\n```\r\nPython 3.9.1 (default, Dec 25 2020, 21:17:19)\r\n[GCC 9.3.0] on linux\r\nType \"help\", \"copyright\", \"credits\" or \"license\" for more information.\r\n>>> import sys\r\n>>> sys.exc_info()\r\n(None, None, None)\r\n```",
    "closed_at": "2020-12-27T22:45:34Z",
    "closed_by": {
        "avatar_url": "https://avatars.githubusercontent.com/u/11248604?v=4",
        "events_url": "https://api.github.com/users/munrad/events{/privacy}",
        "followers_url": "https://api.github.com/users/munrad/followers",
        "following_url": "https://api.github.com/users/munrad/following{/other_user}",
        "gists_url": "https://api.github.com/users/munrad/gists{/gist_id}",
        "gravatar_id": "",
        "html_url": "https://github.com/munrad",
        "id": 11248604,
        "login": "munrad",
        "node_id": "MDQ6VXNlcjExMjQ4NjA0",
        "organizations_url": "https://api.github.com/users/munrad/orgs",
        "received_events_url": "https://api.github.com/users/munrad/received_events",
        "repos_url": "https://api.github.com/users/munrad/repos",
        "site_admin": false,
        "starred_url": "https://api.github.com/users/munrad/starred{/owner}{/repo}",
        "subscriptions_url": "https://api.github.com/users/munrad/subscriptions",
        "type": "User",
        "url": "https://api.github.com/users/munrad"
    },
    "comments": 9,
    "comments_url": "https://api.github.com/repos/ipython/ipython/issues/12742/comments",
    "created_at": "2020-12-26T10:58:09Z",
    "events_url": "https://api.github.com/repos/ipython/ipython/issues/12742/events",
    "html_url": "https://github.com/ipython/ipython/issues/12742",
    "id": 774857703,
    "labels": [],
    "labels_url": "https://api.github.com/repos/ipython/ipython/issues/12742/labels{/name}",
    "locked": false,
    "milestone": {
        "closed_at": "2021-03-27T00:04:01Z",
        "closed_issues": 39,
        "created_at": "2021-01-30T02:20:01Z",
        "creator": {
            "avatar_url": "https://avatars.githubusercontent.com/u/335567?v=4",
            "events_url": "https://api.github.com/users/Carreau/events{/privacy}",
            "followers_url": "https://api.github.com/users/Carreau/followers",
            "following_url": "https://api.github.com/users/Carreau/following{/other_user}",
            "gists_url": "https://api.github.com/users/Carreau/gists{/gist_id}",
            "gravatar_id": "",
            "html_url": "https://github.com/Carreau",
            "id": 335567,
            "login": "Carreau",
            "node_id": "MDQ6VXNlcjMzNTU2Nw==",
            "organizations_url": "https://api.github.com/users/Carreau/orgs",
            "received_events_url": "https://api.github.com/users/Carreau/received_events",
            "repos_url": "https://api.github.com/users/Carreau/repos",
            "site_admin": false,
            "starred_url": "https://api.github.com/users/Carreau/starred{/owner}{/repo}",
            "subscriptions_url": "https://api.github.com/users/Carreau/subscriptions",
            "type": "User",
            "url": "https://api.github.com/users/Carreau"
        },
        "description": "on-merge: backport to 7.x",
        "due_on": "2021-01-30T08:00:00Z",
        "html_url": "https://github.com/ipython/ipython/milestone/82",
        "id": 6370043,
        "labels_url": "https://api.github.com/repos/ipython/ipython/milestones/82/labels",
        "node_id": "MDk6TWlsZXN0b25lNjM3MDA0Mw==",
        "number": 82,
        "open_issues": 0,
        "state": "closed",
        "title": "7.20",
        "updated_at": "2021-04-21T05:59:34Z",
        "url": "https://api.github.com/repos/ipython/ipython/milestones/82"
    },
    "node_id": "MDU6SXNzdWU3NzQ4NTc3MDM=",
    "number": 12742,
    "performed_via_github_app": null,
    "reactions": {
        "+1": 44,
        "-1": 0,
        "confused": 0,
        "eyes": 0,
        "heart": 1,
        "hooray": 0,
        "laugh": 0,
        "rocket": 0,
        "total_count": 45,
        "url": "https://api.github.com/repos/ipython/ipython/issues/12742/reactions"
    },
    "repository_url": "https://api.github.com/repos/ipython/ipython",
    "state": "closed",
    "state_reason": "completed",
    "timeline_url": "https://api.github.com/repos/ipython/ipython/issues/12742/timeline",
    "title": "NameError: name 'sys' is not defined",
    "updated_at": "2021-01-30T23:23:44Z",
    "url": "https://api.github.com/repos/ipython/ipython/issues/12742",
    "user": {
        "avatar_url": "https://avatars.githubusercontent.com/u/11248604?v=4",
        "events_url": "https://api.github.com/users/munrad/events{/privacy}",
        "followers_url": "https://api.github.com/users/munrad/followers",
        "following_url": "https://api.github.com/users/munrad/following{/other_user}",
        "gists_url": "https://api.github.com/users/munrad/gists{/gist_id}",
        "gravatar_id": "",
        "html_url": "https://github.com/munrad",
        "id": 11248604,
        "login": "munrad",
        "node_id": "MDQ6VXNlcjExMjQ4NjA0",
        "organizations_url": "https://api.github.com/users/munrad/orgs",
        "received_events_url": "https://api.github.com/users/munrad/received_events",
        "repos_url": "https://api.github.com/users/munrad/repos",
        "site_admin": false,
        "starred_url": "https://api.github.com/users/munrad/starred{/owner}{/repo}",
        "subscriptions_url": "https://api.github.com/users/munrad/subscriptions",
        "type": "User",
        "url": "https://api.github.com/users/munrad"
    }
}