[
    {
        "author_association": "MEMBER",
        "body": "I'm not sure how you got a more advanced version of yargs with lerna v3.16.5, which is still using yargs `^12.0.1`. In any case, upgrade to `lerna@latest` (v3.18.1) and the issue goes away, as I upgraded to yargs `^14.2.0` in 3.18.0.",
        "created_at": "2019-10-18T16:24:16Z",
        "html_url": "https://github.com/lerna/lerna/issues/2306#issuecomment-543820504",
        "id": 543820504,
        "issue_url": "https://api.github.com/repos/lerna/lerna/issues/2306",
        "node_id": "MDEyOklzc3VlQ29tbWVudDU0MzgyMDUwNA==",
        "performed_via_github_app": null,
        "reactions": {
            "+1": 1,
            "-1": 0,
            "confused": 0,
            "eyes": 0,
            "heart": 0,
            "hooray": 0,
            "laugh": 0,
            "rocket": 0,
            "total_count": 1,
            "url": "https://api.github.com/repos/lerna/lerna/issues/comments/543820504/reactions"
        },
        "updated_at": "2019-10-18T16:24:16Z",
        "url": "https://api.github.com/repos/lerna/lerna/issues/comments/543820504",
        "user": {
            "avatar_url": "https://avatars.githubusercontent.com/u/5605?v=4",
            "events_url": "https://api.github.com/users/evocateur/events{/privacy}",
            "followers_url": "https://api.github.com/users/evocateur/followers",
            "following_url": "https://api.github.com/users/evocateur/following{/other_user}",
            "gists_url": "https://api.github.com/users/evocateur/gists{/gist_id}",
            "gravatar_id": "",
            "html_url": "https://github.com/evocateur",
            "id": 5605,
            "login": "evocateur",
            "node_id": "MDQ6VXNlcjU2MDU=",
            "organizations_url": "https://api.github.com/users/evocateur/orgs",
            "received_events_url": "https://api.github.com/users/evocateur/received_events",
            "repos_url": "https://api.github.com/users/evocateur/repos",
            "site_admin": false,
            "starred_url": "https://api.github.com/users/evocateur/starred{/owner}{/repo}",
            "subscriptions_url": "https://api.github.com/users/evocateur/subscriptions",
            "type": "User",
            "url": "https://api.github.com/users/evocateur"
        }
    },
    {
        "author_association": "NONE",
        "body": "I'm seeing this same warning with lerna v3.18.3, so I am still stumped.",
        "created_at": "2019-10-31T05:35:05Z",
        "html_url": "https://github.com/lerna/lerna/issues/2306#issuecomment-548223520",
        "id": 548223520,
        "issue_url": "https://api.github.com/repos/lerna/lerna/issues/2306",
        "node_id": "MDEyOklzc3VlQ29tbWVudDU0ODIyMzUyMA==",
        "performed_via_github_app": null,
        "reactions": {
            "+1": 4,
            "-1": 0,
            "confused": 0,
            "eyes": 0,
            "heart": 0,
            "hooray": 0,
            "laugh": 0,
            "rocket": 0,
            "total_count": 4,
            "url": "https://api.github.com/repos/lerna/lerna/issues/comments/548223520/reactions"
        },
        "updated_at": "2019-10-31T05:35:05Z",
        "url": "https://api.github.com/repos/lerna/lerna/issues/comments/548223520",
        "user": {
            "avatar_url": "https://avatars.githubusercontent.com/u/46939203?v=4",
            "events_url": "https://api.github.com/users/sraisty1c/events{/privacy}",
            "followers_url": "https://api.github.com/users/sraisty1c/followers",
            "following_url": "https://api.github.com/users/sraisty1c/following{/other_user}",
            "gists_url": "https://api.github.com/users/sraisty1c/gists{/gist_id}",
            "gravatar_id": "",
            "html_url": "https://github.com/sraisty1c",
            "id": 46939203,
            "login": "sraisty1c",
            "node_id": "MDQ6VXNlcjQ2OTM5MjAz",
            "organizations_url": "https://api.github.com/users/sraisty1c/orgs",
            "received_events_url": "https://api.github.com/users/sraisty1c/received_events",
            "repos_url": "https://api.github.com/users/sraisty1c/repos",
            "site_admin": false,
            "starred_url": "https://api.github.com/users/sraisty1c/starred{/owner}{/repo}",
            "subscriptions_url": "https://api.github.com/users/sraisty1c/subscriptions",
            "type": "User",
            "url": "https://api.github.com/users/sraisty1c"
        }
    },
    {
        "author_association": "MEMBER",
        "body": "@sraisty1c Which command elicited this warning for you?",
        "created_at": "2019-10-31T18:02:42Z",
        "html_url": "https://github.com/lerna/lerna/issues/2306#issuecomment-548498833",
        "id": 548498833,
        "issue_url": "https://api.github.com/repos/lerna/lerna/issues/2306",
        "node_id": "MDEyOklzc3VlQ29tbWVudDU0ODQ5ODgzMw==",
        "performed_via_github_app": null,
        "reactions": {
            "+1": 0,
            "-1": 0,
            "confused": 0,
            "eyes": 0,
            "heart": 0,
            "hooray": 0,
            "laugh": 0,
            "rocket": 0,
            "total_count": 0,
            "url": "https://api.github.com/repos/lerna/lerna/issues/comments/548498833/reactions"
        },
        "updated_at": "2019-10-31T18:02:42Z",
        "url": "https://api.github.com/repos/lerna/lerna/issues/comments/548498833",
        "user": {
            "avatar_url": "https://avatars.githubusercontent.com/u/5605?v=4",
            "events_url": "https://api.github.com/users/evocateur/events{/privacy}",
            "followers_url": "https://api.github.com/users/evocateur/followers",
            "following_url": "https://api.github.com/users/evocateur/following{/other_user}",
            "gists_url": "https://api.github.com/users/evocateur/gists{/gist_id}",
            "gravatar_id": "",
            "html_url": "https://github.com/evocateur",
            "id": 5605,
            "login": "evocateur",
            "node_id": "MDQ6VXNlcjU2MDU=",
            "organizations_url": "https://api.github.com/users/evocateur/orgs",
            "received_events_url": "https://api.github.com/users/evocateur/received_events",
            "repos_url": "https://api.github.com/users/evocateur/repos",
            "site_admin": false,
            "starred_url": "https://api.github.com/users/evocateur/starred{/owner}{/repo}",
            "subscriptions_url": "https://api.github.com/users/evocateur/subscriptions",
            "type": "User",
            "url": "https://api.github.com/users/evocateur"
        }
    },
    {
        "author_association": "NONE",
        "body": "> I'm seeing this same warning with lerna v3.18.3, so I am still stumped.\r\n\r\nSame here:\r\n`lerna bootstrap --ignore=@cq/*server`",
        "created_at": "2019-11-08T22:05:20Z",
        "html_url": "https://github.com/lerna/lerna/issues/2306#issuecomment-552007444",
        "id": 552007444,
        "issue_url": "https://api.github.com/repos/lerna/lerna/issues/2306",
        "node_id": "MDEyOklzc3VlQ29tbWVudDU1MjAwNzQ0NA==",
        "performed_via_github_app": null,
        "reactions": {
            "+1": 5,
            "-1": 1,
            "confused": 0,
            "eyes": 0,
            "heart": 0,
            "hooray": 0,
            "laugh": 0,
            "rocket": 0,
            "total_count": 6,
            "url": "https://api.github.com/repos/lerna/lerna/issues/comments/552007444/reactions"
        },
        "updated_at": "2019-11-08T22:05:20Z",
        "url": "https://api.github.com/repos/lerna/lerna/issues/comments/552007444",
        "user": {
            "avatar_url": "https://avatars.githubusercontent.com/u/17158760?v=4",
            "events_url": "https://api.github.com/users/Tassfighter/events{/privacy}",
            "followers_url": "https://api.github.com/users/Tassfighter/followers",
            "following_url": "https://api.github.com/users/Tassfighter/following{/other_user}",
            "gists_url": "https://api.github.com/users/Tassfighter/gists{/gist_id}",
            "gravatar_id": "",
            "html_url": "https://github.com/Tassfighter",
            "id": 17158760,
            "login": "Tassfighter",
            "node_id": "MDQ6VXNlcjE3MTU4NzYw",
            "organizations_url": "https://api.github.com/users/Tassfighter/orgs",
            "received_events_url": "https://api.github.com/users/Tassfighter/received_events",
            "repos_url": "https://api.github.com/users/Tassfighter/repos",
            "site_admin": false,
            "starred_url": "https://api.github.com/users/Tassfighter/starred{/owner}{/repo}",
            "subscriptions_url": "https://api.github.com/users/Tassfighter/subscriptions",
            "type": "User",
            "url": "https://api.github.com/users/Tassfighter"
        }
    },
    {
        "author_association": "NONE",
        "body": "I am still seeing this error. Is there any workaround?",
        "created_at": "2020-01-08T13:50:31Z",
        "html_url": "https://github.com/lerna/lerna/issues/2306#issuecomment-572063542",
        "id": 572063542,
        "issue_url": "https://api.github.com/repos/lerna/lerna/issues/2306",
        "node_id": "MDEyOklzc3VlQ29tbWVudDU3MjA2MzU0Mg==",
        "performed_via_github_app": null,
        "reactions": {
            "+1": 0,
            "-1": 0,
            "confused": 0,
            "eyes": 0,
            "heart": 0,
            "hooray": 0,
            "laugh": 0,
            "rocket": 0,
            "total_count": 0,
            "url": "https://api.github.com/repos/lerna/lerna/issues/comments/572063542/reactions"
        },
        "updated_at": "2020-01-08T13:50:31Z",
        "url": "https://api.github.com/repos/lerna/lerna/issues/comments/572063542",
        "user": {
            "avatar_url": "https://avatars.githubusercontent.com/u/1207173?v=4",
            "events_url": "https://api.github.com/users/conor-mac-aoidh/events{/privacy}",
            "followers_url": "https://api.github.com/users/conor-mac-aoidh/followers",
            "following_url": "https://api.github.com/users/conor-mac-aoidh/following{/other_user}",
            "gists_url": "https://api.github.com/users/conor-mac-aoidh/gists{/gist_id}",
            "gravatar_id": "",
            "html_url": "https://github.com/conor-mac-aoidh",
            "id": 1207173,
            "login": "conor-mac-aoidh",
            "node_id": "MDQ6VXNlcjEyMDcxNzM=",
            "organizations_url": "https://api.github.com/users/conor-mac-aoidh/orgs",
            "received_events_url": "https://api.github.com/users/conor-mac-aoidh/received_events",
            "repos_url": "https://api.github.com/users/conor-mac-aoidh/repos",
            "site_admin": false,
            "starred_url": "https://api.github.com/users/conor-mac-aoidh/starred{/owner}{/repo}",
            "subscriptions_url": "https://api.github.com/users/conor-mac-aoidh/subscriptions",
            "type": "User",
            "url": "https://api.github.com/users/conor-mac-aoidh"
        }
    },
    {
        "author_association": "NONE",
        "body": "Issue appears to still be present in v3.20.2 \ud83d\ude41",
        "created_at": "2020-01-17T15:14:55Z",
        "html_url": "https://github.com/lerna/lerna/issues/2306#issuecomment-575666486",
        "id": 575666486,
        "issue_url": "https://api.github.com/repos/lerna/lerna/issues/2306",
        "node_id": "MDEyOklzc3VlQ29tbWVudDU3NTY2NjQ4Ng==",
        "performed_via_github_app": null,
        "reactions": {
            "+1": 7,
            "-1": 0,
            "confused": 0,
            "eyes": 0,
            "heart": 0,
            "hooray": 0,
            "laugh": 0,
            "rocket": 0,
            "total_count": 7,
            "url": "https://api.github.com/repos/lerna/lerna/issues/comments/575666486/reactions"
        },
        "updated_at": "2020-01-17T15:14:55Z",
        "url": "https://api.github.com/repos/lerna/lerna/issues/comments/575666486",
        "user": {
            "avatar_url": "https://avatars.githubusercontent.com/u/49696165?v=4",
            "events_url": "https://api.github.com/users/Joshua-rose/events{/privacy}",
            "followers_url": "https://api.github.com/users/Joshua-rose/followers",
            "following_url": "https://api.github.com/users/Joshua-rose/following{/other_user}",
            "gists_url": "https://api.github.com/users/Joshua-rose/gists{/gist_id}",
            "gravatar_id": "",
            "html_url": "https://github.com/Joshua-rose",
            "id": 49696165,
            "login": "Joshua-rose",
            "node_id": "MDQ6VXNlcjQ5Njk2MTY1",
            "organizations_url": "https://api.github.com/users/Joshua-rose/orgs",
            "received_events_url": "https://api.github.com/users/Joshua-rose/received_events",
            "repos_url": "https://api.github.com/users/Joshua-rose/repos",
            "site_admin": false,
            "starred_url": "https://api.github.com/users/Joshua-rose/starred{/owner}{/repo}",
            "subscriptions_url": "https://api.github.com/users/Joshua-rose/subscriptions",
            "type": "User",
            "url": "https://api.github.com/users/Joshua-rose"
        }
    },
    {
        "author_association": "NONE",
        "body": "ditto seeing this warning in lerna v3.20.2, but we have no yargs that are being configured.",
        "created_at": "2020-01-30T23:11:12Z",
        "html_url": "https://github.com/lerna/lerna/issues/2306#issuecomment-580505295",
        "id": 580505295,
        "issue_url": "https://api.github.com/repos/lerna/lerna/issues/2306",
        "node_id": "MDEyOklzc3VlQ29tbWVudDU4MDUwNTI5NQ==",
        "performed_via_github_app": null,
        "reactions": {
            "+1": 5,
            "-1": 0,
            "confused": 0,
            "eyes": 1,
            "heart": 0,
            "hooray": 0,
            "laugh": 0,
            "rocket": 0,
            "total_count": 6,
            "url": "https://api.github.com/repos/lerna/lerna/issues/comments/580505295/reactions"
        },
        "updated_at": "2020-01-30T23:11:12Z",
        "url": "https://api.github.com/repos/lerna/lerna/issues/comments/580505295",
        "user": {
            "avatar_url": "https://avatars.githubusercontent.com/u/8214060?v=4",
            "events_url": "https://api.github.com/users/YoDaMa/events{/privacy}",
            "followers_url": "https://api.github.com/users/YoDaMa/followers",
            "following_url": "https://api.github.com/users/YoDaMa/following{/other_user}",
            "gists_url": "https://api.github.com/users/YoDaMa/gists{/gist_id}",
            "gravatar_id": "",
            "html_url": "https://github.com/YoDaMa",
            "id": 8214060,
            "login": "YoDaMa",
            "node_id": "MDQ6VXNlcjgyMTQwNjA=",
            "organizations_url": "https://api.github.com/users/YoDaMa/orgs",
            "received_events_url": "https://api.github.com/users/YoDaMa/received_events",
            "repos_url": "https://api.github.com/users/YoDaMa/repos",
            "site_admin": false,
            "starred_url": "https://api.github.com/users/YoDaMa/starred{/owner}{/repo}",
            "subscriptions_url": "https://api.github.com/users/YoDaMa/subscriptions",
            "type": "User",
            "url": "https://api.github.com/users/YoDaMa"
        }
    },
    {
        "author_association": "NONE",
        "body": "I had the same problem with global lerna installation (v3.20.2). Uninstalling and installing again fixed the problem (likely fixed dependencies)",
        "created_at": "2020-04-10T10:25:41Z",
        "html_url": "https://github.com/lerna/lerna/issues/2306#issuecomment-611975067",
        "id": 611975067,
        "issue_url": "https://api.github.com/repos/lerna/lerna/issues/2306",
        "node_id": "MDEyOklzc3VlQ29tbWVudDYxMTk3NTA2Nw==",
        "performed_via_github_app": null,
        "reactions": {
            "+1": 1,
            "-1": 0,
            "confused": 0,
            "eyes": 0,
            "heart": 0,
            "hooray": 0,
            "laugh": 0,
            "rocket": 0,
            "total_count": 1,
            "url": "https://api.github.com/repos/lerna/lerna/issues/comments/611975067/reactions"
        },
        "updated_at": "2020-04-10T10:25:41Z",
        "url": "https://api.github.com/repos/lerna/lerna/issues/comments/611975067",
        "user": {
            "avatar_url": "https://avatars.githubusercontent.com/u/6463364?v=4",
            "events_url": "https://api.github.com/users/levenleven/events{/privacy}",
            "followers_url": "https://api.github.com/users/levenleven/followers",
            "following_url": "https://api.github.com/users/levenleven/following{/other_user}",
            "gists_url": "https://api.github.com/users/levenleven/gists{/gist_id}",
            "gravatar_id": "",
            "html_url": "https://github.com/levenleven",
            "id": 6463364,
            "login": "levenleven",
            "node_id": "MDQ6VXNlcjY0NjMzNjQ=",
            "organizations_url": "https://api.github.com/users/levenleven/orgs",
            "received_events_url": "https://api.github.com/users/levenleven/received_events",
            "repos_url": "https://api.github.com/users/levenleven/repos",
            "site_admin": true,
            "starred_url": "https://api.github.com/users/levenleven/starred{/owner}{/repo}",
            "subscriptions_url": "https://api.github.com/users/levenleven/subscriptions",
            "type": "User",
            "url": "https://api.github.com/users/levenleven"
        }
    },
    {
        "author_association": "NONE",
        "body": "For me it was a problem with global installation. Removed the global package, and used `npx lerna ...` in package root. Fixed it for me.",
        "created_at": "2020-09-11T12:22:30Z",
        "html_url": "https://github.com/lerna/lerna/issues/2306#issuecomment-691061598",
        "id": 691061598,
        "issue_url": "https://api.github.com/repos/lerna/lerna/issues/2306",
        "node_id": "MDEyOklzc3VlQ29tbWVudDY5MTA2MTU5OA==",
        "performed_via_github_app": null,
        "reactions": {
            "+1": 0,
            "-1": 0,
            "confused": 0,
            "eyes": 0,
            "heart": 0,
            "hooray": 0,
            "laugh": 0,
            "rocket": 0,
            "total_count": 0,
            "url": "https://api.github.com/repos/lerna/lerna/issues/comments/691061598/reactions"
        },
        "updated_at": "2020-09-11T12:22:30Z",
        "url": "https://api.github.com/repos/lerna/lerna/issues/comments/691061598",
        "user": {
            "avatar_url": "https://avatars.githubusercontent.com/u/3128881?v=4",
            "events_url": "https://api.github.com/users/Sayan751/events{/privacy}",
            "followers_url": "https://api.github.com/users/Sayan751/followers",
            "following_url": "https://api.github.com/users/Sayan751/following{/other_user}",
            "gists_url": "https://api.github.com/users/Sayan751/gists{/gist_id}",
            "gravatar_id": "",
            "html_url": "https://github.com/Sayan751",
            "id": 3128881,
            "login": "Sayan751",
            "node_id": "MDQ6VXNlcjMxMjg4ODE=",
            "organizations_url": "https://api.github.com/users/Sayan751/orgs",
            "received_events_url": "https://api.github.com/users/Sayan751/received_events",
            "repos_url": "https://api.github.com/users/Sayan751/repos",
            "site_admin": false,
            "starred_url": "https://api.github.com/users/Sayan751/starred{/owner}{/repo}",
            "subscriptions_url": "https://api.github.com/users/Sayan751/subscriptions",
            "type": "User",
            "url": "https://api.github.com/users/Sayan751"
        }
    },
    {
        "author_association": "NONE",
        "body": "I'm using  \"lerna\": \"^3.22.1\" still I see this issue, let me know what is exact solution to resolve this issue",
        "created_at": "2021-01-25T14:24:03Z",
        "html_url": "https://github.com/lerna/lerna/issues/2306#issuecomment-766850480",
        "id": 766850480,
        "issue_url": "https://api.github.com/repos/lerna/lerna/issues/2306",
        "node_id": "MDEyOklzc3VlQ29tbWVudDc2Njg1MDQ4MA==",
        "performed_via_github_app": null,
        "reactions": {
            "+1": 0,
            "-1": 0,
            "confused": 0,
            "eyes": 0,
            "heart": 0,
            "hooray": 0,
            "laugh": 0,
            "rocket": 0,
            "total_count": 0,
            "url": "https://api.github.com/repos/lerna/lerna/issues/comments/766850480/reactions"
        },
        "updated_at": "2021-01-25T14:24:03Z",
        "url": "https://api.github.com/repos/lerna/lerna/issues/comments/766850480",
        "user": {
            "avatar_url": "https://avatars.githubusercontent.com/u/6199252?v=4",
            "events_url": "https://api.github.com/users/sivaraj-v/events{/privacy}",
            "followers_url": "https://api.github.com/users/sivaraj-v/followers",
            "following_url": "https://api.github.com/users/sivaraj-v/following{/other_user}",
            "gists_url": "https://api.github.com/users/sivaraj-v/gists{/gist_id}",
            "gravatar_id": "",
            "html_url": "https://github.com/sivaraj-v",
            "id": 6199252,
            "login": "sivaraj-v",
            "node_id": "MDQ6VXNlcjYxOTkyNTI=",
            "organizations_url": "https://api.github.com/users/sivaraj-v/orgs",
            "received_events_url": "https://api.github.com/users/sivaraj-v/received_events",
            "repos_url": "https://api.github.com/users/sivaraj-v/repos",
            "site_admin": false,
            "starred_url": "https://api.github.com/users/sivaraj-v/starred{/owner}{/repo}",
            "subscriptions_url": "https://api.github.com/users/sivaraj-v/subscriptions",
            "type": "User",
            "url": "https://api.github.com/users/sivaraj-v"
        }
    }
]